name: Deploy to Hetzner via rsync (port 222)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 222 -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 222 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "mkdir -p ${{ secrets.REMOTE_DIR }}/wp-content"

      - name: Rsync wp-content to server
        run: |
          SRC="./wp-content/"
          DEST="${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.REMOTE_DIR }}/wp-content/"
          rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519 -p 222" \
