name: Deploy to Hetzner via rsync 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -p 222 -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts


      - name: Rsync wp-content to server
        run: |
          SRC="./wp-content/"
          DEST="${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:public_html/travelbyticket-staging/wp-content/"
          rsync -uvzr -e "ssh -p 222" --exclude='.git' --exclude='.github/' --exclude='.htaccess' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.REMOTE_DIR }}


      - name: Set correct permissions
        run: |
          ssh -p 222 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "find public_html/travelbyticket-staging/wp-content -type d -exec chmod 755 {} \; && \
             find public_html/travelbyticket-staging/wp-content -type f -exec chmod 644 {} \;"