name: Deploy to Hetzner via rsync (port 222)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RSYNC_RSH: "ssh -p 222"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: |
          ssh -p 222 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "mkdir -p ${{ secrets.REMOTE_DIR }}/wp-content"

      - name: Rsync wp-content to server
        run: |
          SRC="./wp-content/"
          DEST="${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.REMOTE_DIR }}/wp-content/"
          rsync -az --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="*.sql" \
            --exclude="*.sql.gz" \
            --exclude="uploads" \
            "$SRC" "$DEST"
